{% set version = '0.4.2' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-iterpc
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/iterpc_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/iterpc/iterpc_{{ version }}.tar.gz
  sha256: 38bd464042a27536f676e889263eb2c257a431b59083f58cb54473f42ba2071b

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-arrangements >=1.0.0
    - r-gmp >=0.5_12
    - r-iterators
  run:
    - r-base
    - r-arrangements >=1.0.0
    - r-gmp >=0.5_12
    - r-iterators

test:
  commands:
    - $R -e "library('iterpc')"           # [not win]
    - "\"%R%\" -e \"library('iterpc')\""  # [win]

about:
  home: https://randy3k.github.io/iterpc
  dev_url: https://github.com/randy3k/iterpc
  license: GPL-2.0-only
  summary: 'Iterator for generating permutations and combinations. They can be either drawn with
    or without replacement, or with distinct/ non-distinct items (multiset). The generated
    sequences are in lexicographical order (dictionary order). The algorithms to generate
    permutations and combinations are memory efficient. These iterative algorithms enable
    users to process all sequences without putting all results in the memory at the
    same time. The algorithms are written in C/C++ for faster performance. Note: ''iterpc''
    is no longer being maintained. Users are recommended to switch to ''arrangements''.'
  license_family: GPL2
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: iterpc
# Type: Package
# Title: Efficient Iterator for Permutations and Combinations
# Version: 0.4.2
# Date: 2020-01-08
# Author: Randy Lai [aut, cre]
# Maintainer: Randy Lai <randy.cs.lai@gmail.com>
# Authors@R: c( person("Randy", "Lai", , "randy.cs.lai@gmail.com", role = c("aut", "cre")) )
# Description: Iterator for generating permutations and combinations. They can be either drawn with or without replacement, or with distinct/ non-distinct items (multiset). The generated sequences are in lexicographical order (dictionary order). The algorithms to generate permutations and combinations are memory efficient. These iterative algorithms enable users to process all sequences without putting all results in the memory at the same time. The algorithms are written in C/C++ for faster performance. Note: 'iterpc' is no longer being maintained. Users are recommended to switch to 'arrangements'.
# URL: https://randy3k.github.io/iterpc
# License: GPL-2
# Depends: R (>= 3.0.0)
# Imports: iterators, gmp (>= 0.5-12), arrangements (>= 1.0.0)
# Suggests: foreach, testthat, knitr, rmarkdown
# ByteCompile: yes
# RoxygenNote: 6.1.1
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2020-01-08 23:22:25 UTC; randy
# Repository: CRAN
# Date/Publication: 2020-01-10 12:30:02 UTC
